### ISSUE TITLE
Feature request!

### ISSUE THREAD

**Issue by rezpower** [f0e/mpv-cut#2]
First of all a big thanks for this great script. There are many Video editor softwares out there. But non allows me to preview and seek as fast and easy as with MPV and it's really practical to have your cutting software within MPV itself.

I would like to request a new Feature if it's not too complicated to implement. Could you please add the function to TRIM and add an option to toggle between TRIM and SPLIT? This option already exists in suckless-cut. Maybe it can help to check it out.

Also it would be very practical If we could set a costume output folder instead of the original media folder.

Edit: Right now when cutting with your script every cut file gets renamed and have "(cut)" at the beginning of its filename. It would be great if you could add numbers (cut01) (cut02) instead of only cut to make it easier to merge. Right now you need to check all file timestamps which is not practical.

**Comment by bbrother92** [comment]
I think also showing cuts timestamps would nice, sorry for random comment)

**Comment by f0e** [comment]
Thanks for these ideas, I've added them all in [0.0.5](https://github.com/f0e/mpv-cut/releases/tag/v0.0.5).

**Comment by rezpower** [comment]
Thanks a lot for the new options and changes. They all work perfect :)
