### ISSUE TITLE
date modified same as input file 

### ISSUE THREAD

**Issue by petrolsniffa123** [f0e/mpv-cut#3]
is there a possibility to make it so you can keep the date modified the same after cutting a video? like you can with lossless cut 

edit: it only happens when merging the video, is it possible for it to stick to the original date modified?

**Comment by f0e** [comment]
good catch, fixed in [0.0.7](https://github.com/f0e/mpv-cut/releases/tag/v0.0.7).

**Comment by github-account1111** [comment]
Would it be feasible to have the script also preserve date created?
